export const AUTH_ROLES = {
  jobSeeker: {
    id: 'jobSeeker',
    brandLabel: 'workScout',
    loginPath: '/login',
    signupPath: '/signup',
    loginEndpoint: '/auth/job-seeker/login',
    signupEndpoint: '/auth/job-seeker/signup',
    googleLoginEndpoint: '/auth/job-seeker/login/google',
    googleSignupEndpoint: '/auth/job-seeker/signup/google',
    successRedirect: '/dashboard',
    showGoogle: true,
    login: {
      pageTitle: 'Welcome Back',
      pageSubtitle: 'Sign in to your workScout account',
      cardTitle: 'Sign In',
      cardSubtitle: 'Use your email and password to access your account',
      submitLabel: 'Sign In',
      alternatePrompt: "Don't have an account?",
      alternateLabel: 'Sign up',
    },
    signup: {
      pageTitle: 'Create Your Account',
      pageSubtitle: 'Join workScout and find your next opportunity',
      cardTitle: 'Get Started',
      cardSubtitle: 'Create an account with your email or Google',
      submitLabel: 'Create Account',
      alternatePrompt: 'Already have an account?',
      alternateLabel: 'Sign in',
    },
  },
  employer: {
    id: 'employer',
    brandLabel: 'workScout',
    loginPath: '/employer/login',
    signupPath: '/employer/signup',
    loginEndpoint: '/auth/employer/login',
    signupEndpoint: '/auth/employer/signup',
    googleLoginEndpoint: '/auth/employer/login/google',
    googleSignupEndpoint: '/auth/employer/signup/google',
    successRedirect: '/employer/dashboard',
    showGoogle: true,
    login: {
      pageTitle: 'Employer Sign In',
      pageSubtitle: 'Manage job postings on workScout',
      cardTitle: 'Sign In',
      cardSubtitle: 'Use your employer email and password',
      submitLabel: 'Sign In',
      alternatePrompt: "Don't have an employer account?",
      alternateLabel: 'Sign up',
    },
    signup: {
      pageTitle: 'Create Employer Account',
      pageSubtitle: 'Post jobs and reach top talent on workScout',
      cardTitle: 'Get Started',
      cardSubtitle: 'Create your company account with email or Google',
      submitLabel: 'Create Account',
      alternatePrompt: 'Already have an account?',
      alternateLabel: 'Sign in',
    },
  },
  admin: {
    id: 'admin',
    brandLabel: 'workScout',
    loginPath: '/admin/login',
    signupPath: '/admin/signup',
    loginEndpoint: '/auth/admin/login',
    signupEndpoint: '/auth/admin/signup',
    successRedirect: '/dashboard',
    showGoogle: false,
    login: {
      pageTitle: 'Admin Sign In',
      pageSubtitle: 'Secure access to the workScout admin portal',
      cardTitle: 'Sign In',
      cardSubtitle: 'Use your admin email and password',
      submitLabel: 'Sign In',
      alternatePrompt: 'Need an admin account?',
      alternateLabel: 'Sign up',
    },
    signup: {
      pageTitle: 'Create Admin Account',
      pageSubtitle: 'Register a new workScout administrator',
      cardTitle: 'Get Started',
      cardSubtitle: 'Admin accounts use email and password only',
      submitLabel: 'Create Account',
      alternatePrompt: 'Already have an account?',
      alternateLabel: 'Sign in',
    },
  },
};
